apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: myharbor.apps.211-34-231-93.nip.io/mvp/mvp_apigw
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 50Mi
        readinessProbe:
            httpGet:
              path: mvp/actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-lo
        livenessProbe:
            httpGet:
              path: /mvp/actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 300
            timeoutSeconds: 30
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5    
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
